# Generated by Django 3.2.6 on 2021-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('roll_number', models.IntegerField()),
            ],
        ),
    ]
